### ISSUE TITLE
关于在配置页面点击测试按钮生成 阿里云图片生成路径问题

### ISSUE THREAD

**Issue by hainuo** [njzydark/Aragorn#11]
当设置了自定义域名为http://a.b.com  bucket 为xxx的时候
点击测试 后黏贴版地址 会 变成 http://xxx.a.b.com/icon-0b0a7a.png

真正路径为http://a.b.com/icon-0b0a7a.png

**Comment by njzydark** [comment]
返回的地址能访问吗
因为我这里没有在阿里云绑定自定义域名，所以粘贴板的地址我是直接取的sdk返回的地址，没有做特殊处理

**Comment by njzydark** [comment]
不好意思 是我这里的问题 下个版本修复

**Comment by njzydark** [comment]
https://github.com/ali-sdk/ali-oss/issues/894
