### ISSUE TITLE
npm run app:start

### ISSUE THREAD

**Issue by PockyRayzz** [njzydark/Aragorn#13]
![image](https://user-images.githubusercontent.com/29441283/100494689-f02c2f80-317e-11eb-9efb-55955d100b6a.png)

试着清楚了appdata下的缓存，依然这样..

**Comment by njzydark** [comment]
跟缓存没关系 目测是这行代码报错了 [https://github.com/njzydark/Aragorn/blob/46306a6c28bd48b50f8b6e3ec1e1a61e85ae2e99/packages/aragorn-app-main/src/windowManager.ts#L42](https://github.com/njzydark/Aragorn/blob/46306a6c28bd48b50f8b6e3ec1e1a61e85ae2e99/packages/aragorn-app-main/src/windowManager.ts#L42)

但是我这里复现不了 一切正常

**Comment by njzydark** [comment]
你的代码不是目前最新的吧 请更新至最新版本 这个报错问题10.3号之后就修复了

**Comment by PockyRayzz** [comment]
我直接clone的master分支

**Comment by njzydark** [comment]
你看下这个路径 packages/aragorn-app-main/src/windowManager.ts 代码是否与目前master分支的代码一致

**Comment by PockyRayzz** [comment]
一致的，这个问题主要是我翻过stackoverflow也没找到类似的解决方案，所以也不确定是我的机器环境问题还是代码问题

**Comment by njzydark** [comment]
报错就是这里的错 https://github.com/njzydark/Aragorn/blob/46306a6c28bd48b50f8b6e3ec1e1a61e85ae2e99/packages/aragorn-app-main/src/windowManager.ts#L42

**Comment by PockyRayzz** [comment]
我看README支持windows，一开始是下载了预发布的winodws安装包，发现也是这个错，结果clone到本地也是这个错误... 也许是我机器环境问题

**Comment by njzydark** [comment]
你下载最新打包好的包运行会不会报错 https://github.com/njzydark/Aragorn/releases/tag/v1.0.0-beta.11

**Comment by njzydark** [comment]
> 我看README支持windows，一开始是下载了预发布的winodws安装包，发现也是这个错，结果clone到本地也是这个错误... 也许是我机器环境问题

我想确认一下你现在本地的代码是不是我目前最新的 还是之前clone下来的 之前clone下来的如果在10.3号之前是有这个问题的

**Comment by PockyRayzz** [comment]
Aragorn-Setup-1.0.0-beta.11.exe
这个是打包好的，同样的错误。
以及本地代码是同步的，如图：
![image](https://user-images.githubusercontent.com/29441283/100495784-da703780-3189-11eb-92e0-baf6e80b965b.png)

**Comment by njzydark** [comment]
windows系统什么版本

**Comment by PockyRayzz** [comment]
Windows 10企业版LTSC，版本号：1809。操作系统版本：17763.107

**Comment by njzydark** [comment]
不好意思 是我的代码问题

在之前升级 `webpack5` 的过程中我把 `.babelrc` 配置中的 `targets` 由原来的 `node: true`改为了 `electron: 10` 从而导致 optional-chaining 无效 目前已经改回来了 https://github.com/njzydark/Aragorn/commit/17822a120cef0d04e5429ad1f3a655f726dbf3c2

你拉取最新的代码或者下载最新打包好的的 beta12 即可解决
