### ISSUE TITLE
自定义域名不支持变量么？ 

### ISSUE THREAD

**Issue by hbyxzpf** [njzydark/Aragorn#5]

**Comment by hbyxzpf** [comment]
文件删除失败 connect ECONNREFUSED 还有个貌似github的api 有频率限制

**Comment by njzydark** [comment]
> 文件删除失败 connect ECONNREFUSED 还有个貌似github的api 有频率限制

这个是网络问题 我本地测试的时候因为开了透明代理 所以没遇到这个问题 下个版本会支持设置http proxy

自定义域名变量是啥意思，自动复制的文件链接后缀添加query参数？
