### ISSUE TITLE
big sur无法使用

### ISSUE THREAD

**Issue by sunleonx** [njzydark/Aragorn#6]
![image](https://user-images.githubusercontent.com/38236663/92101079-2c195800-ee0f-11ea-8dc2-945c319c3793.png)

**Comment by njzydark** [comment]
任意源开了吗 [开启任意源](https://jingyan.baidu.com/article/9f63fb9162e3e6c8400f0e30.html)

**Comment by sunleonx** [comment]
> 任意源开了吗 [开启任意源](https://jingyan.baidu.com/article/9f63fb9162e3e6c8400f0e30.html)

开启了的
![image](https://user-images.githubusercontent.com/38236663/92109762-2d9d4d00-ee1c-11ea-8b4a-58870c856e22.png)

**Comment by sunleonx** [comment]
zip

> 你是直接下载的dmg安装包吗

zip包

**Comment by njzydark** [comment]
腾讯云是最近刚支持的，beta3上

**Comment by njzydark** [comment]
> > 你是直接下载的dmg安装包吗
> 
> 我看你的readme里面支持腾讯云，刚刚试了下载dmg可以运行，但里面没有腾讯云的配置

beta.3已发布 [https://github.com/njzydark/Aragorn/releases/tag/v1.0.0-beta.3](https://github.com/njzydark/Aragorn/releases/tag/v1.0.0-beta.3)
