### ISSUE TITLE
package.json 缺失 dev的配置

### ISSUE THREAD

**Issue by tanliyuan** [njzydark/Aragorn#8]
没有列出全局安装的依赖，其他人没法运行

**Comment by njzydark** [comment]
README 已经说的很清楚了，执行以下两步：

```bash
npm i
npm run setup
```

这里特别说明一下：

1. 项目是使用 [lerna](https://lerna.js.org/) 进行管理的，根目录的 package.json 只是公共开发依赖，不包含项目所有依赖
2. npm i 只是把公共依赖装上
3. npm run setup 会把所有 packages 里的依赖全部装上
